---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.7
  - name: centos-7.0
  - name: fedora-20

suites:
  - name: default
    run_list: recipe[locale]
    attributes:
      locale:
        lc_all: "C"
